#!/usr/bin/env node
/**
 * Bundles `src/index.js` into the single ES module TEDI loads.
 *
 * The host reads exactly one file - whatever `manifest.main` names - and
 * imports it as one ES module. There is no transpile step at install or at
 * runtime, so the output must be plain ES2022.
 *
 *   node build.mjs            one-shot build
 *   node build.mjs --watch    rebuild on every src/ change
 *
 * The output is a build artifact: it is gitignored and rebuilt in CI into the
 * release zip, so the repo only ever holds readable `src/` modules.
 *
 * Nothing in here is per-extension. The entry point, the output path and the
 * banner are all read from `manifest.json`, so this file is byte-identical
 * across every TEDI extension and can be copied forward without edits.
 */
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build, context } from "esbuild";

const root = path.dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(readFileSync(path.join(root, "manifest.json"), "utf8"));

// `manifest.main` is the contract with the host; deriving the outfile from it
// means a manifest rename can never leave the host importing a stale bundle.
const outfile = path.join(root, manifest.main ?? "extension.js");

/** @type {import("esbuild").BuildOptions} */
const options = {
  entryPoints: [path.join(root, "src", "index.js")],
  outfile,
  bundle: true,
  // The loader does `import(blobUrl)` and reads the `activate` / `deactivate`
  // exports, so the output has to stay a real ES module.
  format: "esm",
  platform: "browser",
  target: "es2022",
  charset: "utf8",
  legalComments: "none",
  // Unminified on purpose: the bundle is what a user reviewing an extension
  // before install actually reads, and the size saved is irrelevant next to a
  // webview that already has React in it.
  minify: false,
  logLevel: "info",
  banner: {
    js: [
      `// ${manifest.name} ${manifest.version} - @generated by build.mjs, DO NOT EDIT.`,
      "// Source lives in src/; run `npm run build` after editing.",
      ...(manifest.homepage ? [`// ${manifest.homepage}`] : []),
    ].join("\n"),
  },
};

if (process.argv.includes("--watch")) {
  const ctx = await context(options);
  await ctx.watch();
  console.log(`[build] watching src/ -> ${path.basename(outfile)} (Ctrl+C to stop)`);
} else {
  await build(options);
  console.log(`[build] wrote ${path.basename(outfile)}`);
}
